/**
 * Reads the built UI assets (JS + CSS) from dist/ui/assets/ and generates
 * a TypeScript source file that exports them as string constants.
 *
 * This runs AFTER the UI build and BEFORE the server tsup build, so the
 * embedded strings end up in the published bundle — no fs/path/__dirname
 * needed at runtime.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const serverPkg = join(__dirname, "..");
const uiPkg = join(serverPkg, "..", "ui");
const uiAssetsDir = join(uiPkg, "dist", "assets");

const jsContent = readFileSync(join(uiAssetsDir, "index.js"), "utf-8");
const cssContent = readFileSync(join(uiAssetsDir, "index.css"), "utf-8");

const output = `// Auto-generated by scripts/embed-ui.js — do not edit manually
export const UI_JS = ${JSON.stringify(jsContent)};
export const UI_CSS = ${JSON.stringify(cssContent)};
`;

writeFileSync(join(serverPkg, "src", "ui-assets.ts"), output, "utf-8");
console.log("Embedded UI assets into src/ui-assets.ts");
